# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spectrum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spectrum.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0espectrum.proto\"\xa6\x01\n\x08Spectrum\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05x_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_min\x18\x04 \x01(\x02\x12\r\n\x05y_max\x18\x05 \x01(\x02\x12\x14\n\x08\x63hannels\x18\x06 \x03(\x02\x42\x02\x10\x01\x12\x11\n\x05power\x18\x07 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x04sd_l\x18\x08 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x04sd_u\x18\t \x03(\x02\x42\x02\x10\x01\x62\x06proto3')
)




_SPECTRUM = _descriptor.Descriptor(
  name='Spectrum',
  full_name='Spectrum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Spectrum.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_min', full_name='Spectrum.x_min', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_max', full_name='Spectrum.x_max', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_min', full_name='Spectrum.y_min', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_max', full_name='Spectrum.y_max', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='Spectrum.channels', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='Spectrum.power', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sd_l', full_name='Spectrum.sd_l', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sd_u', full_name='Spectrum.sd_u', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['Spectrum'] = _SPECTRUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Spectrum = _reflection.GeneratedProtocolMessageType('Spectrum', (_message.Message,), dict(
  DESCRIPTOR = _SPECTRUM,
  __module__ = 'spectrum_pb2'
  # @@protoc_insertion_point(class_scope:Spectrum)
  ))
_sym_db.RegisterMessage(Spectrum)


_SPECTRUM.fields_by_name['channels']._options = None
_SPECTRUM.fields_by_name['power']._options = None
_SPECTRUM.fields_by_name['sd_l']._options = None
_SPECTRUM.fields_by_name['sd_u']._options = None
# @@protoc_insertion_point(module_scope)
