# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spectrogram.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spectrogram.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11spectrogram.proto\"[\n\x0bSpectrogram\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61seline\x18\x02 \x01(\t\x12\x14\n\x0cpolarisation\x18\x03 \x01(\t\x12\x11\n\x05phase\x18\x04 \x03(\x05\x42\x02\x10\x01\"1\n\x0cSpectrograms\x12!\n\x0bspectrogram\x18\x01 \x03(\x0b\x32\x0c.Spectrogramb\x06proto3')
)




_SPECTROGRAM = _descriptor.Descriptor(
  name='Spectrogram',
  full_name='Spectrogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Spectrogram.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='baseline', full_name='Spectrogram.baseline', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='polarisation', full_name='Spectrogram.polarisation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phase', full_name='Spectrogram.phase', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=112,
)


_SPECTROGRAMS = _descriptor.Descriptor(
  name='Spectrograms',
  full_name='Spectrograms',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spectrogram', full_name='Spectrograms.spectrogram', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=163,
)

_SPECTROGRAMS.fields_by_name['spectrogram'].message_type = _SPECTROGRAM
DESCRIPTOR.message_types_by_name['Spectrogram'] = _SPECTROGRAM
DESCRIPTOR.message_types_by_name['Spectrograms'] = _SPECTROGRAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Spectrogram = _reflection.GeneratedProtocolMessageType('Spectrogram', (_message.Message,), dict(
  DESCRIPTOR = _SPECTROGRAM,
  __module__ = 'spectrogram_pb2'
  # @@protoc_insertion_point(class_scope:Spectrogram)
  ))
_sym_db.RegisterMessage(Spectrogram)

Spectrograms = _reflection.GeneratedProtocolMessageType('Spectrograms', (_message.Message,), dict(
  DESCRIPTOR = _SPECTROGRAMS,
  __module__ = 'spectrogram_pb2'
  # @@protoc_insertion_point(class_scope:Spectrograms)
  ))
_sym_db.RegisterMessage(Spectrograms)


_SPECTROGRAM.fields_by_name['phase']._options = None
# @@protoc_insertion_point(module_scope)
