# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spectrogram.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11spectrogram.proto\"[\n\x0bSpectrogram\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61seline\x18\x02 \x01(\t\x12\x14\n\x0cpolarization\x18\x03 \x01(\t\x12\x11\n\x05phase\x18\x04 \x03(\x05\x42\x02\x10\x01\"1\n\x0cSpectrograms\x12!\n\x0bspectrogram\x18\x01 \x03(\x0b\x32\x0c.Spectrogramb\x06proto3')



_SPECTROGRAM = DESCRIPTOR.message_types_by_name['Spectrogram']
_SPECTROGRAMS = DESCRIPTOR.message_types_by_name['Spectrograms']
Spectrogram = _reflection.GeneratedProtocolMessageType('Spectrogram', (_message.Message,), {
  'DESCRIPTOR' : _SPECTROGRAM,
  '__module__' : 'spectrogram_pb2'
  # @@protoc_insertion_point(class_scope:Spectrogram)
  })
_sym_db.RegisterMessage(Spectrogram)

Spectrograms = _reflection.GeneratedProtocolMessageType('Spectrograms', (_message.Message,), {
  'DESCRIPTOR' : _SPECTROGRAMS,
  '__module__' : 'spectrogram_pb2'
  # @@protoc_insertion_point(class_scope:Spectrograms)
  })
_sym_db.RegisterMessage(Spectrograms)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPECTROGRAM.fields_by_name['phase']._options = None
  _SPECTROGRAM.fields_by_name['phase']._serialized_options = b'\020\001'
  _SPECTROGRAM._serialized_start=21
  _SPECTROGRAM._serialized_end=112
  _SPECTROGRAMS._serialized_start=114
  _SPECTROGRAMS._serialized_end=163
# @@protoc_insertion_point(module_scope)
